### ISSUE TITLE
How to parse attachments

### ISSUE THREAD

**Issue by heri16** [awetzel/mailibex#4]
How do I get attachments from an email binary?

**Comment by awetzel** [comment]
hello @heri16 : 
First use `MimeMail.from_string(mail_bin)` to get the *MimeMail* tree struct, of your email, then .  This gives you the exact "parsed" version of your email, then you can apply selectively some `decode_headers` functions to parse on demand some type of headers. And `decode_body` to decode the body.

```elixir
m = mail |> MimeMail.decode_body |> MimeMail.Emails.decode_headers
               |> MimeMail.CTParams.decode_headers |> MimeMail.Words.decode_headers
```

then you can browser the MimeMail tree to get your attachments.

But since the *low level* API is necessary for DKIM signature for instance, it is cumbersome for basic email parsing. So the `MimeMail.Flat` module allows you to "flatten" the mimemail tree in order to easily retreive your attachments : instead of having a %Mimemail{headers: [kwlist],body: treeof-MimeMail} you handle a single kwlist (actually the headers kwlist) with the body tree as keyword key-values with special key `:txt,:html,:attach,:attach_in,:include` according to the shape of the body tree. 

For instance, to get an included attachment : 

```elixir
(mail_bin |> MimeMail.from_string |> MimeMail.Flat.from_mail)[:include]
```

if there are several included attachments : 

```elixir
mail_bin |> MimeMail.from_string |> MimeMail.Flat.from_mail |> Enum.filter(&elem(&1,0) == :include)
```

**Comment by heri16** [comment]
A little surprised that attachments don't have a Stream or GenStage based
interface. Nevertheless, thanks for this useful library. Please see my pull
requests.
